storage/app/public/dependencies/controller-positions.json

Fix ESSEX_APP frequency in controller positions

Fix #14 Essex Frequency

---

storage/app/public/dependencies/airfield-ownership.json
storage/app/public/dependencies/controller-positions.json

- Fixes a number of frequency and top-down problems.

Frequency updates

---

app/Libraries/GeneralSquawkRuleGenerator.php
database/migrations/2019_02_09_192604_define_ccams_ranges.php

Add Missing CCAMS Ranges

---

storage/app/public/dependencies/airfield-ownership.json
storage/app/public/dependencies/controller-positions.json

Fix  #27
Add SOLENT_APP to controller positions and airfield ownership.

Fix #27: Solent Doesnt Exist

---

database/migrations/2019_02_24_221334_add_redhill_squawk.php

- Adds Redhill conspicuity squawk

Fix #32: Add Redhill Squawks

---

database/migrations/2019_07_21_152050_airac1909.php

Close #46 
- Update Bristol Squawk Ranges
(Note, will need full deploy of the Laravel Upgrade as these haven't gone out yet)

Update Bristol Squawk Ranges

---

database/migrations/2020_02_01_113600_heathrow_real_ops_holds.php

Fix #68: Migration For New Heathrow Realops Holds

---

.styleci.yml
app/Http/Controllers/AirfieldController.php
app/Http/Controllers/SidController.php
app/Models/Airfield/Airfield.php
app/Models/Controller/Handoff.php
app/Models/Controller/Prenote.php
app/Models/Sid.php
app/Services/AirfieldService.php
app/Services/HandoffService.php
app/Services/PrenoteService.php
database/migrations/2020_01_30_202040_airac_202002_aerodrome_updates.php
database/migrations/2020_01_30_202040_airac_202002_clacton_splits.php
database/migrations/2020_01_30_202040_airac_202002_daventry_splits.php
database/migrations/2020_01_30_202040_airac_202002_redfa_handoffs.php
database/migrations/2020_01_30_202040_airac_202002_tcne_splits.php
database/migrations/2020_02_01_171300_handoff_dependencies.php
database/seeds/SidTableSeeder.php
routes/api.php
tests/BaseApiTestCase.php
tests/BaseFunctionalTestCase.php
tests/app/Http/Controllers/DependencyControllerTest.php
tests/app/Http/Controllers/HandoffControllerTest.php
tests/app/Http/Controllers/SidControllerTest.php
tests/app/Services/AirfieldServiceTest.php
tests/app/Services/HandoffServiceTest.php
tests/app/Services/PrenoteServiceTest.php
tests/app/Services/SidServiceTest.php
tests/app/Services/UserServiceTest.php

Close #66 
- Also adds the handoff dependencies.

202002 New Style

---

app/Http/Controllers/GithubController.php
database/seeds/DatabaseSeeder.php
database/seeds/SectorFileIssuesTableSeeder.php
tests/app/Http/Controllers/GithubControllerTest.php

80 gihtub race 2

---

app/Http/Controllers/GithubController.php

Adds an extra check to make absolutely sure we're not spamming issues.

Just. One. More. Check.

---

app/Events/RegionalPressuresUpdatedEvent.php

- Make a property public so that pressures are properly broadcast.

Fix RPS Broadcast

---

app/Console/Kernel.php
app/Http/Controllers/GithubController.php
app/Http/Middleware/GithubAuth.php
app/Models/Airfield/Airfield.php
database/migrations/2019_09_28_203124_add_more_missing_airfields.php
database/migrations/2020_02_08_123000_hold_restriction_keys.php
database/migrations/2020_02_08_123100_new_doncaster_sids.php
database/migrations/2020_02_08_123100_new_farnborough_holds.php
database/migrations/2020_02_08_123100_new_farnborough_sids.php
database/migrations/2020_02_08_123100_new_farnborough_squawks.php
database/migrations/2020_02_08_123100_new_heathrow_sids.php
database/migrations/2020_02_29_123100_new_handoffs.php
database/seeds/DatabaseSeeder.php
database/seeds/SectorFileIssuesTableSeeder.php
tests/BaseApiTestCase.php
tests/app/Http/Controllers/GithubControllerTest.php
tests/app/Http/Middleware/GithubAuthTest.php

- Fix a few merge things and update some data in develop prior to API v2.0

Develop master merge pre v2

---

app/Http/Controllers/TeapotController.php
routes/api.php
tests/app/Http/Controllers/TeapotControllerTest.php

- Return 200 on API Auth to make sure we're not causing any weird issues by relying on 418

Return 200 On API Authorisation

---

database/migrations/2020_03_29_174000_add_edinburgh_delivery.php

Add Edinburgh Delivery

---

database/migrations/2020_03_29_175412_remove_southampton_ground.php

Remove Southampton Ground

---

database/migrations/2020_03_29_180102_switch_tweed_to_tartn.php

Fix #107: Replace TWEED With TARTN

---

database/migrations/2020_03_29_180600_doncaster_sid_updates.php

Fix #104: EGCN SID Updates

---

app/Exceptions/Handler.php
bootstrap/app.php
composer.json
composer.lock
tests/app/Http/Controllers/VersionControllerTest.php
tests/app/Models/Squawks/AllocationHistoryTest.php
tests/app/Models/Version/VersionTest.php

Close #121 
- Upgrade to Laravel 7
- Upgrade to PHPUnit 9

121 laravel 7

---

app/Console/Commands/CleanSquawkAllocations.php
app/Helpers/User/UserConfig.php
app/Providers/RegionalPressureServiceProvider.php
app/Services/MetarService.php
config/metar.php
config/squawk.php
database/seeds/SquawkAllocationTableSeeder.php
tests/app/Console/Commands/CleanSquawkAllocationsTest.php
tests/app/Helpers/User/UserConfigTest.php
tests/app/Services/MetarServiceTest.php
tests/app/Services/UserConfigServiceTest.php

128 fix config cache

---

app/Services/AirfieldService.php
app/Services/DependencyService.php
database/migrations/2020_04_23_195443_update_military_positions.php
database/migrations/2020_04_23_201252_fix_manchester_top_down.php
database/migrations/2020_04_23_202447_add_lands_end_top_down.php
database/migrations/2020_04_23_205519_add_scilly_positions_and_ownership.php
database/migrations/2020_04_23_210257_add_brize_lars_position.php
database/migrations/2020_04_23_210737_add_brize_director_position.php
database/migrations/2020_04_23_211444_add_missing_top_downs.php
tests/app/Services/AirfieldServiceTest.php

- Fix London Mil
- Fix EGCC Top Down
- Add EGHC_TWR and Top Downs
- Add EGHE Positions and Top Downs
- Add Brize LARS
- Add Brize Director
- Misc new positions / top downs

Airac updates 2020 05

---

.gitignore
app/Console/Commands/SrdImport.php
app/Console/Kernel.php
app/Http/Controllers/SrdController.php
app/Imports/SrdImport.php
app/Imports/SrdNotesImport.php
app/Imports/SrdRoutesImport.php
app/Models/Srd/SrdNote.php
app/Models/Srd/SrdRoute.php
composer.json
composer.lock
config/app.php
config/filesystems.php
database/migrations/2020_04_16_193753_create_srd_routes_table.php
database/migrations/2020_04_18_110359_create_srd_notes_table.php
database/migrations/2020_04_18_164747_create_srd_note_srd_route_table.php
database/seeds/DatabaseSeeder.php
database/seeds/SrdRoutesTableSeeder.php
database/seeds/SrdTableSeeder.php
routes/api.php
storage/app/.gitignore
tests/BaseApiTestCase.php
tests/app/Http/Controllers/SrdControllerTest.php
tests/app/Imports/SrdNotesImportTest.php
tests/app/Imports/SrdRoutesImportTest.php

- Import SRD routes from the XLS file.
- Allow the data to be queried.

SRD Route Import and Querying

---

app/Http/Controllers/SrdController.php
tests/app/Http/Controllers/SrdControllerTest.php

- Change it to an array instead of an object. So much nicer to validate.

Change Note Return Format

---

composer.json
composer.lock

As per https://github.com/beyondcode/laravel-websockets/blob/master/CHANGELOG.md
1.4 required for Laravel 7

Bump Pusher

---

database/migrations/2020_05_23_131123_southend_pdr_updates.php
database/migrations/2020_05_23_131945_farnborough_sid_updates.php

- Update Southend PDR designators
- Update Farnborough SID designators

Airac 2020 07

---

app/Allocator/Squawk/General/AirfieldPairingSquawkAllocator.php
database/migrations/2020_07_30_162402_channel_islands_domestic_ranges.php
tests/app/Allocator/Squawk/General/AirfieldPairingSquawkAllocatorTest.php
tests/app/Listeners/Network/RecordFirEntryTest.php

216 channel islands domestic

---

app/Console/Kernel.php
phpunit.xml

- Migrate to new PHPUnit Schema
- Don't overlap networkdata:update tasks

General maintenance

---

app/Console/Commands/SrdImport.php
app/Console/Commands/WakeCategoriesImport.php
app/Console/Kernel.php
app/Exceptions/InvalidWakeImportException.php
app/Imports/Srd/SrdImport.php
app/Imports/Srd/SrdNotesImport.php
app/Imports/Srd/SrdRoutesImport.php
app/Imports/Wake/Importer.php
app/Models/Dependency/Dependency.php
tests/app/Console/Commands/WakeCategoriesImportTest.php
tests/app/Imports/Srd/SrdNotesImportTest.php
tests/app/Imports/Srd/SrdRoutesImportTest.php
tests/app/Imports/Wake/ImporterTest.php

- Add command to pull in wake category data from the UK Wake Category Spreadsheet

Wake types updated

---

database/migrations/2020_09_21_195255_add_new_mpc_positions.php

Fix #265: MPC Splits

---

app/Listeners/Hold/UnassignHoldOnDisconnect.php
app/Listeners/Squawk/MarkAssignmentDeletedOnDisconnect.php
app/Listeners/Squawk/MarkAssignmentHistoryDeletedOnUnassignment.php
app/Listeners/Stand/DeleteAssignmentHistoryOnUnassignment.php
app/Listeners/Stand/TriggerUnassignmentOnDisconnect.php
app/Providers/EventServiceProvider.php
app/Providers/SquawkServiceProvider.php
app/Services/NetworkDataService.php
database/migrations/2020_10_03_085246_add_network_data_updated_index.php
tests/app/Listeners/Squawk/MarkAssignmentDeletedOnDisconnectTest.php
tests/app/Listeners/Squawk/MarkAssignmentDeletedOnUnassignmentTest.php
tests/app/Listeners/Stand/MarkAssignmentDeletedOnUnassignmentTest.php
tests/app/Listeners/Stand/TriggerDepartureUnassignmentOnceAirborneTest.php
tests/app/Listeners/Stand/TriggerUnassignmentOnDisconnectTest.php

- Stop stand unassignments spamming every time an aircraft disconnects.

275 stand unassignments

---

database/migrations/2020_11_29_160741_scottish_msl_calculations.php

Update Scottish MSL Calculations

---

database/migrations/2020_11_29_020111_swanwick_mil__sectorisation_update.php

- Created/Removed everything stated in the post: https://community.vatsim.uk/topic/37499-2020-12-03-swanwick-mil-sectorisation-and-frequency-change/

Added Swanwick new sectoring and top down

---

database/migrations/2020_11_17_163631_change_pc_bandbox_frequency.php
database/migrations/2020_11_17_163820_add_pc_sector29.php
database/migrations/2020_11_17_164334_add_pc_trent.php
database/migrations/2020_11_17_165951_add_pc_penil.php
database/migrations/2020_11_17_170644_tc_midlands_tc_north_west_updates.php
database/migrations/2020_11_17_171658_fix_heathrow_tc_north_west_departure_handoffs.php
database/migrations/2020_11_17_180754_fix_wallasey_ownership.php

309 mpc frequency changes

---

database/migrations/2020_11_07_181638_deancross_frequency_change.php

Fix #292: Deancross Frequency

---

app/Services/StandService.php

Increase Occupancy Detection Distance

---

database/migrations/2020_12_27_202346_bristol_stand_priority.php

Bristol Stand Priorities

---

app/Http/Controllers/NotificationController.php
app/Models/Notification/Notification.php
database/migrations/2021_01_21_155342_create_notifications_table.php
database/migrations/2021_01_21_170224_create_notification_controllers_table.php
database/migrations/2021_01_21_175205_create_notification_reads_table.php
routes/api.php
tests/app/Http/Controllers/NotificationControllerTest.php

This PR adds the start of a very basic notification system.
- A notification can be created with a title and body
- A notification can have a validity period (`valid_from` and `valid_to`)
- A notification can be disabled regardless of whether it is within its validty
- A notification can be associated to controller positions
- A notification can be read by a user
- A user can retrieve a list of all valid notifications
- A user can retrieve a list of valid notifications that are unread
I've done my best to follow the conventions, but I think there is some de-duplication and extraction that can be done before this is merged.

Notifications System

---

app/Services/StandService.php

Gives us a bit more room to play with for people that have dodgy scenery

Increase Stand Occupancy Distance

---

app/Http/Controllers/Admin/StandAdminController.php
app/Models/Airfield/Airfield.php
docs/api/admin-functions.yml
routes/api.php
tests/app/Http/Controllers/Admin/StandAdminControllerTest.php

Add endpoint to provide index for airfields with stands. Has endpoint to view ones only with stands, and then a query param to list all.

Add endpoint to list airfields with or without stands

---

database/migrations/2021_03_23_172943_add_more_holds.php

Add New Holds

---

database/migrations/2021_03_24_163843_create_new_gatwick_heathrow_departures.php

Add New EGKK -> EGLL/WU SIDs

---

database/migrations/2021_03_25_162609_west_lag_splits.php

Update West LAG Splits

---

database/migrations/2021_04_04_152348_add_exter_initial_altitudes.php

fix(exter): add exter initial altitudes

---

database/migrations/2021_04_07_151656_create_failed_jobs_table.php
database/migrations/2021_04_07_151811_create_job_batches_table.php

fix(jobs): add missing failed jobs table

---

composer.lock

May address issues around scaling and stale connections
https://github.com/beyondcode/laravel-websockets/pull/708

fix(websocket): bump laravel websocket version

---

.github/dependabot.yml

build(deps): Include JS in dependabot

---

app/Models/Sid.php
app/Services/SidService.php
database/migrations/2021_04_14_160257_add_initial_heading_to_sid_table.php
database/migrations/2021_04_14_160437_add_initial_heading_data.php
tests/app/Http/Controllers/SidControllerTest.php
tests/app/Services/SidServiceTest.php

Adds an initial heading that can be set by EuroScope for SIDs
Re #416

feat(sid): add initial headings for SIDs

---

app/Http/Controllers/Admin/NavaidAdminController.php
app/Http/Controllers/NavaidController.php
app/Http/Requests/NavaidRequest.php
app/Jobs/Hold/RemoveAssignmentsForAircraftLeavingHold.php
app/Listeners/Network/NetworkDataUpdated.php
app/Models/Hold/AssignedHold.php
app/Models/Navigation/Navaid.php
app/Services/HoldService.php
app/Services/SectorfileService.php
database/migrations/2021_04_18_145430_convert_navaid_coordinate_format.php
database/seeds/NavaidTableSeeder.php
docs/admin/admin-functions.yml
tests/app/Http/Controllers/Admin/NavaidAdminControllerTest.php
tests/app/Http/Controllers/NavaidControllerTest.php
tests/app/Jobs/Hold/RemoveAssignmentsForAircraftLeavingHoldTest.php
tests/app/Listeners/Network/NetworkDataUpdatedTest.php
tests/app/Services/HoldServiceTest.php
tests/app/Services/SectorfileServiceTest.php

feat(holds): Remove stale hold assignments

---

database/migrations/2021_05_04_161026_add_missing_heathrow_stands.php
database/migrations/2021_05_04_170715_add_missing_stansted_stands.php

Missing stands

---

config/horizon.php

Trying to tame memory usage on the horizon worker(s).

Horizon Performance Changes

---

app/Console/Commands/CleanDepartureReleaseRequestHistory.php
app/Console/Commands/OptimiseTables.php
app/Console/Kernel.php
app/Http/Requests/Release/Departure/RequestDepartureRelease.php
app/Models/Release/Departure/DepartureReleaseRequest.php
database/migrations/2021_05_23_132259_add_departure_release_requests_indexes.php
tests/app/Console/Commands/CleanDepartureReleaseRequestHistoryTest.php
tests/app/Http/Controllers/DepartureReleaseControllerTest.php
tests/app/Models/Release/Departure/DepartureReleaseRequestTest.php

- Add some indexes to the departure release requests table
- Prevent departure release requests being created if one is already active
- Clean the departure release request tables periodically

Departure release tidyups

---

app/Console/Kernel.php

Overlaps were causing issues with files getting deleted.

fix(srd): Fix SRD Schedule

---

.github/dependabot.yml

build(dependabot): make dependabot use yarn

---

.docker/web/Dockerfile

We need it so we can run the migrations

chore(docker): install mysql on dev docker for dev building

---

tests/app/Http/Controllers/DepartureReleaseControllerTest.php

It was causing tests to periodically fail

test(departure-release): set test time on CarbonImmutable

---

database/migrations/2021_06_21_161606_add_london_area_north_splits.php
database/migrations/2021_06_21_164307_rename_manchester_positions.php
database/migrations/2021_06_21_164623_update_norwich_topdown.php

- Add LON_NW_CTR, which supersedes LON_N in top-down and handoff priorities except for EGSH.
- Rename MAN_U and MAN_S to MAN_WU and MAN_SE respectively.
- Add LON_NE_CTR, with top-down priority over LON_N for EGSH

564 ac north west

---

.github/workflows/release.yml
.github/workflows/test.yml
package.json
yarn.lock

584 semantic release dev dependencies

---

database/migrations/2021_07_17_112822_aldergrove_radar_frequency.php

Was updated 15/07/2021
fix #601

chore(controller-positions): update Aldergrove Radar Frequency

---

app/Http/Controllers/ControllerPositionController.php
app/Http/Controllers/SidController.php
app/Services/ControllerService.php
app/Services/DependencyService.php
database/migrations/2021_07_17_114449_remove_initial_altitudes_dependency.php
database/migrations/2021_07_17_114925_remove_controller_positions_v1_dependency.php
routes/api.php
tests/app/Http/Controllers/ControllerPositionControllerTest.php
tests/app/Http/Controllers/SidControllerTest.php
tests/app/Services/ControllerServiceTest.php
tests/app/Services/DependencyServiceTest.php

Stop supporting old dependencies that are no longer required by the plugin and remove code associated with them to reduce confusion.

feat(dependencies): Delete old dependencies

---

app/Http/Controllers/Admin/StandAdminController.php
app/Models/Airfield/Airfield.php
app/Models/Airfield/Terminal.php
docs/admin/admin-functions.yml
routes/api.php
tests/app/Http/Controllers/Admin/StandAdminControllerTest.php

This PR aims to cater for a 'per-terminal' administration for airfields such as LL & CC.

feat: Add endpoint to get stands by terminal

---

app/Services/SrdService.php
tests/app/Services/SrdServiceTest.php

fix(srd): fix SRD download URL

---

database/migrations/2021_08_12_194514_jetblue_heathrow_stands.php

data(stands): add JetBlue Heathrow Stand Assignments

---

database/migrations/2021_08_12_195625_royal_suite_assignments.php

45X stands with 457 highest priority, descending, skipping 451
Fix #620

data(stands): add heathrow corporate and executive stand assignment

---

app/Models/Airfield/Airfield.php
database/migrations/2021_08_13_145147_change_airfield_coordinate_column_type.php

Using doubles was making them go skew-whiff and breaking the odd test

fix(airfield): fix rounding errors on airfield coordinates

---

database/migrations/2021_08_24_200130_east_midlands_stand_refresh.php

New stands, new assignments
fix #641

data(stands): east midlands stand refresh

---

app/Services/SrdService.php
tests/app/Services/SrdServiceTest.php

fix(srd): Update SRD download url

---

database/migrations/2021_11_07_150730_military_squawk_ranges.php

data(military): leeming and culdrose squawk ranges

---

app/Rules/VatsimCallsign.php
tests/app/Http/Controllers/SquawkControllerTest.php
tests/app/Rules/VatsimCallsignTest.php

fix(callsigns): Increase length of VATSIM callsigns to new network limit

---

app/Console/Commands/OptimiseTables.php
app/Console/Kernel.php

fix(database): prune failed jobs daily

---

app/Services/NetworkMetadataService.php
tests/app/Services/NetworkMetadataServiceTest.php

fix(network): invalid json from network metadata

---

app/Models/Hold/Hold.php
database/migrations/2021_12_19_205447_cardiff_hold_inbound_course.php

data(holds): update cardiff hold inbound heading

---

database/migrations/2021_12_19_210210_edinburgh_stand_closures.php

data(edinburgh): close edinburgh stands 9A, 10A, 209 for allocation

---

app/Console/Kernel.php

fix(kernel): Remove schedule monitor sync

---

app/Services/RunwayService.php

fix(runways): Remove PHP 8 specific syntax

---

database/migrations/2022_01_21_171735_allow_prenotes_to_tower.php

Any tower position that has a GND/DEL underneath it should be able to have prenotes sent to it.

data(prenotes): Allow prenotes to certain tower positions

---

database/migrations/2022_01_24_165926_gatwick_biggin_departure_rename.php

data(sids): make gatwick biggin departures non runway specific

---

database/migrations/2022_01_27_172428_hold_inbound_updates.php

data(holds): 2201 hold updates

---

database/migrations/2022_01_29_140855_stansted_a380_stands.php

data(stands): Stansted A380 stands

---

database/migrations/2022_02_05_152334_wake_scheme_intervals_dependency_table.php

Need to include schemes and intervals
fix #821

fix(dependencies): add missing tables for wake scheme dependency

---

database/migrations/2022_02_07_193301_glasgow_jet2_stands.php

They were given the wrong airline (ESX).
Fixes #830

fix(stands): Fix Jet2 Glasgow Allocations

---

app/Models/Sid.php
database/migrations/2022_02_05_151659_stansted_sid_changes.php

Updates to climb profile means new identifiers
resolve #818

data(stansted): stansted sid identifier updates

---

database/migrations/2022_02_05_135934_stansted_radar_positions.php
database/migrations/2022_02_05_140925_stansted_enroute_top_down.php
database/migrations/2022_02_05_145838_london_midlands_callsigns.php

data(controllers): Stansted positions and top down

---

app/Models/Stand/Stand.php
tests/app/Models/Stand/StandTest.php

fix(stand): handle aircraft with no UK WTC in arrival stand allocation

---

app/Services/HoldService.php
tests/app/Services/HoldServiceTest.php

Aircraft can be in a hold up to 12nm, but wont class as entered until within 3nm.

feat(hold): reduce hold entry distance

---

database/migrations/2022_03_04_173536_remove_stansted_nugbo_prenote.php

No longer required.
Resolves #866

data(prenotes): remove stansted NUGBO prenotes

---

database/migrations/2022_04_10_134425_bristol_stand_changes.php

data(stands): Bristol stand updates

---

database/migrations/2022_04_16_145437_play_airline_stands.php

data(stands): Play EGSS Stands

---

database/migrations/2022_04_20_205442_fix_intention_code_dependency_path.php

fix(intention): Intention code dependency path

---

database/migrations/2022_04_24_170853_recat_eu_code_changes.php
database/seeds/AircraftTableSeeder.php
tests/app/Imports/Wake/RecatImporterTest.php
tests/app/Services/AircraftServiceTest.php

data(wake): Update recat category codes

---

database/migrations/2022_05_11_212200_renumber_heathrow_stands.php

data(stands): Update heathrow stand designation

---

app/Services/IntentionCode/Builder/CodeBuilder.php
app/Services/IntentionCode/Builder/ConditionBuilder.php
app/Services/IntentionCode/Builder/IntentionCodeBuilder.php
app/Services/IntentionCode/Builder/PriorityBuilder.php
database/factories/IntentionCode/IntentionCodeFactory.php
database/migrations/2022_04_16_160541_add_intention_code_data.php
database/migrations/2022_05_13_180637_update_e2_exit_code.php
tests/app/Services/IntentionCode/Builder/CodeBuilderTest.php
tests/app/Services/IntentionCode/Builder/ConditionBuilderTest.php
tests/app/Services/IntentionCode/Builder/IntentionCodeBuilderTest.php
tests/app/Services/IntentionCode/Builder/PriorityBuilderTest.php
tests/app/Services/IntentionCode/Condition/AnyOfTest.php
tests/app/Services/IntentionCode/Condition/NotTest.php

- Make it possible to use intention code builders from an existing model
- Allow conditions to be removed
- Update the E2 condition to be cruising above 29000
Resolve #907

907 e2 intention code change

---

app/Models/Stand/Stand.php
database/migrations/2022_05_11_214313_east_midlands_stands.php

Resolves #915
For release with 2205

data(stands): East midlands updates

---

database/migrations/2022_06_02_205312_essex_hold_updates.php

data(holds): update essex holds

---

app/Services/ControllerService.php
tests/app/Services/ControllerServiceTest.php

Remove the code as its no longer a thing.

chore: remove unused dependency code for airfield ownership

---

app/Filament/Resources/UserResource.php

Fix the user searching function so it searches the right columns

fix: user searching in filament admin

---

composer.json
composer.lock

Can be bumped back up again once https://github.com/filamentphp/filament/pull/3789 is released

Filament version fix

---

app/Filament/Resources/VersionResource.php
app/Filament/Resources/VersionResource/Pages/ListVersions.php
app/Policies/PluginVersionPolicy.php
app/Providers/AuthServiceProvider.php
lang/en/table.php
lang/en/versions/table.php
tests/app/Filament/VersionResourceTest.php
tests/app/Policies/PluginVersionPolicyTest.php

- Lets us see plugin versions
- Lets us "decommission" plugin versions, should a bug be released that would cause crashes or breakages.

Plugin version admin

---

.env.example
.github/workflows/deploy.yml
app/Console/Kernel.php
app/Exceptions/Handler.php
app/Http/Kernel.php
app/Providers/AppServiceProvider.php
composer.json
composer.lock
config/app.php
config/bugsnag.php
config/logging.php

- Retains Sentry for performance monitoring
- Adds Bugsnag for error monitoring
- Bugsnag deploy/release tracking is handled in Forge

Bugsnag for Error Monitoring

---

app/Console/Commands/OptimiseTables.php
app/Console/Kernel.php

I don't think this is fixing our current issue with OhDear, but the table is 2 million+ rows and 300+mb in size, so no harm in pruning it.

fix: prune schedule monitor daily

---

app/Filament/Resources/AirlineResource/RelationManagers/TerminalsRelationManager.php

fix: airline terminal table crash

---

app/Models/AltimeterSettingRegions/AltimeterSettingRegion.php
app/Services/RegionalPressureService.php
database/migrations/2023_05_04_165358_add_offset_to_altimeter_setting_regions_table.php
database/migrations/2023_05_04_172704_change_adjustments_for_tmas.php
tests/app/Services/RegionalPressureServiceTest.php

Allows a configurable adjustment instead of a simple -1 on RPS's.

feat: RPS calculation adjustment

---

app/Filament/Pages/UserCreateKey.php
app/Http/Controllers/Auth/CoreAuthController.php
app/Providers/AuthServiceProvider.php
app/Services/UserConfigCreatorInterface.php
app/Services/UserConfigService.php
resources/views/filament/pages/user-create-key.blade.php
tests/app/Filament/Pages/UserCreateKeyTest.php
tests/app/Http/Controllers/Auth/CoreAuthControllerTest.php

- Create hidden page that automatically creates an access token and redirects the user to the provided URL
- Redirect users to intended destination after login
Related to https://github.com/VATSIM-UK/uk-controller-plugin/pull/519

Token issuing inline

---

app/Http/Livewire/RequestAStandForm.php
app/Models/Stand/Stand.php
app/Services/Stand/StandStatusService.php

Query performance

---

.devcontainer/devcontainer.json

Adds .devcontainer configuration

dev: add devcontainer.json

---

app/Allocator/Stand/OrdersStandsByCommonConditions.php
app/Allocator/Stand/SelectsStandsUsingStandardConditions.php

PHP 8.1 can't have traits with constants.

fix: traits with constants

---

app/Filament/Resources/AirfieldResource/Pages/EditAirfield.php
database/migrations/2023_10_10_164308_update_index_on_airfield_visual_reference_point_table.php
database/migrations/2023_10_23_180544_change_foreign_key_on_msl_airfield.php
tests/app/Filament/AirfieldResourceTest.php

fix: allow airfield deletions where airfield has msl

---

database/factories/Stand/StandFactory.php

test: restrict fixture stand ids

---

app/Filament/Resources/PluginLogResource.php
app/Filament/Resources/PluginLogResource/Pages/ListPluginLogs.php
app/Filament/Resources/PluginLogResource/Pages/ViewPluginLog.php
app/Http/Controllers/PluginLogController.php
app/Http/Requests/Plugin/PluginLog.php
app/Models/Plugin/PluginLog.php
app/Providers/AuthServiceProvider.php
config/filament-logger.php
database/factories/Plugin/PluginLogFactory.php
database/migrations/2024_04_14_132135_create_plugin_logs_table.php
database/seeds/DatabaseSeeder.php
database/seeds/PluginLogTableSeeder.php
lang/en/form.php
lang/en/plugin/form.php
lang/en/plugin/table.php
lang/en/table.php
routes/api.php
tests/app/Filament/PluginLogResourceTest.php
tests/app/Http/Controllers/PluginLogControllerTest.php

Adds an endpoint to capture logs from the plugin to allow fatal exceptions and other problems to be diagnosed.

feat: endpoint to capture logs from plugin

---

docs/guides/StandAllocation.md
lang/en/stands/form.php

Adds warning text around domestic/international for stands.

fix: domestic international stand warning

---

app/Console/Commands/UserCreate.php
app/Helpers/Vatsim/VatsimCidValidator.php
app/Http/Controllers/UserController.php
app/Http/Middleware/VatsimCid.php
app/Http/Requests/User/CreateUser.php
app/Rules/User/VatsimCid.php
app/Services/Stand/StandReservationService.php
app/Services/UserService.php
routes/api.php
tests/app/Helpers/Vatsim/VatsimCidValidatorTest.php
tests/app/Http/Controllers/UserControllerTest.php
tests/app/Rules/User/VatsimCidTest.php
tests/app/Services/UserServiceTest.php

Adds an endpoint to create users without also creating their plugin config.

feat: user creation without config

---

app/Models/Vatsim/NetworkAircraft.php
app/Services/Stand/ArrivalAllocationService.php
tests/app/Services/Stand/ArrivalAllocationServiceTest.php

Fixes regression in https://github.com/VATSIM-UK/uk-controller-api/pull/1556

fix: dont assign arrival stands if aircraft not seen in last minute

---

app/Services/Metar/MetarRetrievalService.php
tests/app/Services/Metar/MetarRetrievalServiceTest.php
tests/app/Services/Metar/MetarServiceTest.php

No longer appears to support encoding.

Fix METAR Download
