- app/Services/SquawkService.php
It wasn't properly shuffling the ranges and always selecting the first one.
> Fix Squawk Range Selection

- database/migrations/2019_09_14_094017_update_gatwick_departures.php
- database/migrations/2019_09_14_094914_update_cambridge_squawk_range.php
- storage/app/public/dependencies/airfield-ownership.json
- storage/app/public/dependencies/controller-positions.json
Close #49 
- Update Cambridge Squawk Rangers
- Update Gatwick Non-RNAV Departures
- Add New Scottish Sectors
- Add New TC East Splits
- Update Scottish TMA Frequencies
- Add missing top-downs for EGPA and EGPC
- Added Manchester Wallasey Sector
- Changed EGCC Ownership To MAN_W
- Fixed Top Down Order on EGAA
- Added EGAA INT to Top Down For EGAC
> Airac 201910

- storage/app/public/dependencies/controller-positions.json
Closes #54 
- Adds TC JACKO and TC DAGGA
- Updates London sector frequencies
- #53 supersedes, this is a backup if required
> Airac 201911

- app/Services/SquawkService.php
- tests/app/Services/SquawkServiceTest.php
- Add the missing event to properly trigger squawk auditing.
> Fire Squawk Assignment Event

- app/Allocator/Squawk/General/AirfieldPairingSquawkAllocator.php
- app/Allocator/Squawk/General/CcamsSquawkAllocator.php
- app/Allocator/Squawk/General/OrcamSquawkAllocator.php
- app/Allocator/Squawk/Local/UnitDiscreteSquawkAllocator.php
- app/Providers/EventServiceProvider.php
- app/Services/NetworkDataService.php
- database/seeds/NetworkAircraftTableSeeder.php
Fix #198 
- Stops squawk integrity violations from happening by locking the ranges during an insert.
- Registers missing events for audit purposes.
> Prevent squawk integrity violations

- .docker/web/Dockerfile
- .docker/web/etc/nginx/conf.d/ukcp.conf
- .docker/web/etc/nginx/nginx.conf
- .docker/web/etc/supervisor/conf.d/nginx.conf
- .docker/web/etc/supervisor/conf.d/php-fpm.conf
- .docker/web/etc/supervisor/conf.d/websockets.conf
- .docker/web/etc/supervisor/supervisord.conf
- .docker/web/usr/local/etc/php/conf.d/local.ini
- .env.example
- config/broadcasting.php
- database/migrations/2021_01_11_204954_add_heathrow_terminals.php
- docker-compose.yml
- docs/README.md
Fix #374 
Uses #369 
Creates terminals, assigns airlines and stands to them at Heathrow so that if specific airline stands aren't available, they get parked at the correct terminal.
> 374 heathrow terminal fallback

- tests/app/Models/Stand/StandTest.php
PHP 8.0 changes its transaction model - this removes the truncates in tests, so we don't violate the transactions.
> PHP 8.0 Test Transactions Fix

- app/Allocator/Stand/AbstractArrivalStandAllocator.php
- app/Allocator/Stand/AirlineArrivalStandAllocator.php
- app/Allocator/Stand/AirlineDestinationArrivalStandAllocator.php
- app/Allocator/Stand/AirlineTerminalArrivalStandAllocator.php
- app/Allocator/Stand/CargoArrivalStandAllocator.php
- app/Allocator/Stand/DomesticInternationalStandAllocator.php
- app/Allocator/Stand/FallbackArrivalStandAllocator.php
- app/Allocator/Stand/GeneralUseArrivalStandAllocator.php
- app/Allocator/Stand/ReservedArrivalStandAllocator.php
- database/migrations/2021_02_18_210430_assign_shuttle_stands_to_ba_domestic.php
- Apply wake-based stand allocation preference after any bespoke ones. Not doing this caused lots of BA flights to prefer T3 instead of T5 at Heathrow.
- Mark all SHT stands at LL as available to BAW with an origin of `EG`
> Stand allocation fun

- app/Console/Commands/DataAdminCreate.php
- app/Console/Kernel.php
- app/Http/Kernel.php
- app/Providers/AuthServiceProvider.php
- app/Services/UserService.php
- docs/README.md
- routes/api.php
- tests/app/Console/Commands/DataAdminCreateTest.php
- tests/app/Services/UserServiceTest.php
This PR adds the concept of a 'data admin' scope to the auth process. This is to facilitate upcoming work where
a separate service will administer the data contained within UKCP.
The motivation for keeping it seperate from existing 'admin' auth is to ensure the other service doesn't have
more responsibility than it needs.
> Scaffold data management auth

- .github/workflows/deploy.yml
Rather than populating the `.env` file within GitHub Actions based on a secret, we'll keep it on the server and symlink it into each release. This gives us a little more flexibility on the control of the file.
_Note: The .env file has been copied to the application root directory on our production server so this PR can be merged without any risks once approved._
> Move .env From GitHub to Server

- .docker/web/Dockerfile
- .docker/web/etc/supervisor/supervisord.conf
Run supervisorctl in docker so we can restart services in dev
> build(docker): allow running of supervisorctl

- app/Broadcaster/PluginEventBroadcaster.php
To deal with the fact that Pusher is crashing a lot.
> fix(websocket): Do plugin events before pusher

- app/Events/DepartureReleaseApprovedEvent.php
- app/Http/Requests/Release/Departure/ApproveDepartureRelease.php
- app/Jobs/Release/Departure/CancelOutstandingDepartureReleaseRequests.php
- app/Jobs/Release/Departure/CancelRequestsForDepartedAircraft.php
- app/Listeners/Network/NetworkDataUpdated.php
- app/Models/Controller/ControllerPosition.php
- app/Models/Release/Departure/DepartureReleaseRequest.php
- app/Models/Vatsim/NetworkAircraft.php
- app/Providers/NetworkServiceProvider.php
- app/Services/DepartureReleaseService.php
- database/factories/Controller/ControllerPositionFactory.php
- database/factories/Release/Departure/DepartureReleaseRequestFactory.php
- database/factories/Vatsim/NetworkAircraftFactory.php
- tests/app/Events/DepartureReleaseApprovedEventTest.php
- tests/app/Http/Controllers/DepartureReleaseControllerTest.php
- tests/app/Jobs/Release/Departure/CancelOutstandingDepartureReleaseRequestsTest.php
- tests/app/Jobs/Release/Departure/CancelRequestsForDepartedAircraftTest.php
- tests/app/Listeners/Network/NetworkDataUpdatedTest.php
- tests/app/Services/DepartureReleaseServiceTest.php
- Cancel departure release requests if aircraft disconnected
- Cancel departure release requests if aircraft is now airborne
- Allow departure release requests to have infinite approval time (up until one of the above requirements becomes false)
> No release expiries

- .github/workflows/deploy.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
As per https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/.
> Migrate to GitHub Actions Concurrency

- app/Services/NetworkDataService.php
- tests/app/Services/NetworkDataServiceTest.php
Sometimes we get an insane squawk code from the datafeed, so ignore any data containing this
fix #553
> fix(networkdata): handle invalid transponder from datafeed

- app/Helpers/Sectorfile/Coordinate.php
- app/Http/Controllers/NavaidController.php
- app/Services/SectorfileService.php
- tests/app/Services/SectorfileServiceTest.php
It puts 60 seconds instead of increasing the minutes by 1
fix #552
> fix(sectorfile): handle invalid seconds in sectorfile coordinates

- app/Allocator/Squawk/AbstractSquawkAllocator.php
- app/Http/Controllers/HoldController.php
- app/Models/Vatsim/NetworkAircraft.php
- app/Services/NetworkDataService.php
- app/Services/StandService.php
- database/factories/Vatsim/NetworkAircraftFactory.php
- database/migrations/2021_06_19_144633_network_aircraft_transponder_updated_at_default.php
- tests/app/Http/Controllers/StandControllerTest.php
- tests/app/Jobs/Stand/TriggerUnassignmentOnDisconnectTest.php
- tests/app/Services/NetworkDataServiceTest.php
- tests/app/Services/StandServiceTest.php
In a transaction (e.g. when assigning squawks), NetworkDataService can hit an integrity violation on updateOrCreate but then not subsequently find the aircraft in the database. This switches it for an Upsert so it works.
> 556 squawk return value error

- database/factories/Vatsim/NetworkAircraftFactory.php
It was causing an issue with duplicate primary keys
fix #591
> test(networkaircraft): add unique constraint on faker for network aircraft

- app/Services/VersionService.php
- tests/app/Services/VersionServiceTest.php
We dont need to keep them around now due to automatic updates
fix #586
> refactor(version): mark all versions as deleted upon new release

- database/migrations/2021_07_13_153842_update_channel_island_domestic_squawks.php
Part of the range has been taken away for other uses
fix #598
> chore(squawks): update channel island domestic squawk ranges

- database/migrations/2021_07_17_113147_southampton_standard_departures.php
Adds the intial altitudes and handoff orders for all EGHI departures in the UKSF.
fix #506
> chore(sids): add southampton standard departures and handoff order

- package.json
Lots of important things were being missed from the changelogs. Created an extra category of commit
called  "data" which pertains to data updates for the plugin-side. Also updated commitizen config.
> chore(releases): update commitizen and release configs for better documentation

- app/Services/NetworkDataService.php
- tests/app/Services/NetworkDataServiceTest.php
We get in a bit of a loop when creating placeholder aircraft, so lets not do that.
> fix(network): fix phantom aircraft caused by network aircraft loop

- app/Models/Vatsim/NetworkAircraft.php
- app/Services/NetworkDataService.php
- tests/app/Console/Commands/AllocateStandForArrivalTest.php
- tests/app/Services/NetworkDataServiceTest.php
- tests/app/Services/SquawkServiceTest.php
- tests/app/Services/StandServiceTest.php
Overlapping jobs post-timeout could cause exceptions due to MySQL foreign key issues. Fix this by adding a global scope to network aircraft so only active ones are selected for querying.
fix #634
fix #555
> fix(networkdata): data races with timing out aircraft

- app/Services/StandService.php
Potential overlaps with aircraft deletion and not eager-loading relations can cause a field to come
out as null
fix #637
> fix(stands): fix issue with job overlap

- tests/app/Http/Controllers/Admin/StandAdminControllerTest.php
The models are getting inaccurate longitudes - probably because they're returned straight from eloquent and not the db. This refreshes the collection so we get exactly whats in the DB.
> test(stands): Fix flakey test

- app/Http/Controllers/Admin/StandAdminController.php
- app/Models/Stand/Stand.php
- app/Services/StandAdminService.php
- app/Services/StandService.php
- database/migrations/2021_09_10_083341_add_closed_at_to_stands_table.php
- database/migrations/2021_09_10_084143_close_gatwick_pier6_stands.php
- docs/admin/admin-functions.yml
- routes/api.php
- tests/app/Http/Controllers/Admin/StandAdminControllerTest.php
- tests/app/Models/Stand/StandTest.php
- tests/app/Services/StandServiceTest.php
Airfields do renovation work, stands get closed and we choose to replicate this on the SMRs. Therefore the automatic stand allocator should not allow stands that are closed to be allocated.
> feat(stands): Allow stands to be temporarily closed

- .github/workflows/dependabot-merge.yml
- .github/workflows/test.yml
Save me the effort of merging dependabot every week... auto merge anything that is a minor or patch version from dependabot as soon as it passes CI.
> build(actions): Auto merge minor dependabot revisions

- app/Events/MetarsUpdatedEvent.php
- tests/app/Events/MetarsUpdatedEventTest.php
The plugin expects push events to be an object, with underlying data. The MetarsUpdatedEvent was
returning a JSON array. This change makes it return an object instead.
fix #774
> fix(metars): broadcast metar data in the correct format

- database/migrations/2022_01_20_194507_east_midlands_cargo_priority.php
East midland Cargo default is to prefer West apron if no specific stand requirements, so make the West apron just that little bit more appealing to the allocator than the east.
> data(stands): EGNX cargo stand priority

- app/Console/Kernel.php
- app/Services/Metar/MetarRetrievalService.php
- tests/app/Services/Metar/MetarRetrievalServiceTest.php
- tests/app/Services/Metar/MetarServiceTest.php
Metars get cached by .net so we need to make the request a little different each time.
Fixes #790
> fix(metars): Fix metar caching

- database/migrations/2022_01_25_195231_recat_intermediate_intervals.php
They're the same, but we need them for the wake calculator.
Fixes #806
> data(wake): Add intermediate recat intervals

- database/migrations/2022_02_07_191417_controller_frequency_conversions.php
This is now possible with velocity. Should be deployed either on the 23rd or
very early on the 24th for airac day. This includes both enroute and aerodrome
positions as it makes sense to do them all at once.
Resolve #828
Resolve #817
> data(controllers): Update controller positions to properly reflect 25khz spacing

- app/Allocator/Stand/AirlineArrivalStandAllocator.php
- app/Allocator/Stand/AirlineCallsignSlugArrivalStandAllocator.php
- app/Models/Airline/Airline.php
- app/Models/Stand/Stand.php
- app/Providers/StandServiceProvider.php
- app/Services/AirlineService.php
- database/migrations/2022_02_28_173512_add_fly_uk_airline.php
- database/migrations/2022_02_28_173819_add_callsign_slug_to_airline_stand_table.php
- database/migrations/2022_02_28_174007_fly_uk_stand_assignments.php
- tests/app/Allocator/Stand/AirlineCallsignSlugStandAllocatorTest.php
- tests/app/Models/Stand/StandTest.php
- tests/app/Services/AirlineServiceTest.php
- tests/app/Services/Stand/StandServiceTest.php
- Add mechanism to allocate airline stands based on the callsign slug (the bit after the airline).
- Add stand allocations for Fly UK (UKV) based on slugs.
Resolve #857
> feat(stand): Allocate stands based on airline callsigns, add UKV preferred

- database/migrations/2022_05_11_213212_ban_msfs_default_squawk.php
- tests/app/Services/SquawkServiceTest.php
> fix(squawks): prevent assignment of msfs default squawk

- app/Http/Controllers/DependencyController.php
- app/Providers/RouteServiceProvider.php
- routes/api.php
- tests/BaseApiTestCase.php
- tests/app/Console/Commands/DataAdminCreateTest.php
- tests/app/Console/Commands/UserAdminCreateTest.php
- tests/app/Http/Controllers/AuthenticationTest.php
- tests/app/Http/Controllers/DependencyControllerTest.php
- tests/app/Http/Middleware/AuthenticateTest.php
- tests/app/Http/Middleware/LogAdminActionTest.php
- tests/app/Http/Middleware/UserIsBannedTest.php
- tests/app/Http/Middleware/UserIsDisabledTest.php
- tests/app/Services/UserServiceTest.php
- tests/app/Services/UserTokenServiceTest.php
Traditional Laravel APIs have `/api` as the root of the API routes. UKCP traditionally avoided this as originally we were a Lumen application with no "web" side. To make the project more relatable to other devs, this change makes all the api routes take the prefix `api`. Conversely, all the "web" routes no longer bear the prefix `/web`.
BREAKING CHANGE: This will change all the API routes so the plugin will need to be updated to account for this.
> feat: make api the root of the api

- app/Filament/Resources/StandResource/RelationManagers/PairedStandsRelationManager.php
The id column (which doesn't add very much) on the paired stand table would cause an ambiguous reference in the SQL clause. So to make things work, remove that column.
> fix(admin): Ambiguous id on paired stand search

- app/Filament/Resources/SquawkAssignmentResource.php
- app/Filament/Resources/SquawkAssignmentResource/Pages/ListSquawkAssignments.php
- config/filament-logger.php
- lang/en/squawks/table.php
- lang/en/table.php
- tests/app/Filament/AccessCheckingHelpers/ChecksListingFilamentAccess.php
- tests/app/Filament/SquawkAssignmentResourceTest.php
Allow users to view all the squawk assignments over at ukcp.vatsim.uk.
> feat: list squawk assignments in the plugin

- lang/en/squawks/form.php
Adds a missing translation string for the Unit Squawk Ranges admin panels.
> Squawk range label unit discrete

- lang/en/stands/table.php
Name the column "origin", which more accurately reflects what the column is.
Fix #1139
> fix: stand airlines column name

- app/Filament/Resources/IntentionCodeResource.php
- lang/en/intention/form.php
Prevents an intention code from having more than 1 FIR exit point as a condition. This is necessary to make things simpler on the plugin-side with regards to sending integration messages to vStrips etc.
> feat: only allow one fir exit point per intention code

- app/Services/Stand/StandAssignmentsService.php
Fixes an error with integrity constraints when users assign the stand before the API has a chance to see the aircraft in the network feed.
> Create network aircraft for stand assignments

- app/Models/User/User.php
Changes the Filament logging so that we only log changes to users that we care about (status, firstname, lastname).
> fix: dont log unnecessary changes to users

- app/Filament/Resources/AirlineResource.php
- app/Filament/Resources/AirlineResource/Pages/CreateAirline.php
- app/Filament/Resources/AirlineResource/Pages/EditAirline.php
- app/Filament/Resources/AirlineResource/Pages/ListAirlines.php
- app/Filament/Resources/AirlineResource/Pages/ViewAirline.php
- app/Filament/Resources/AirlineResource/RelationManagers/StandsRelationManager.php
- app/Filament/Resources/AirlineResource/RelationManagers/TerminalsRelationManager.php
- app/Models/Airfield/Terminal.php
- app/Models/Airline/Airline.php
- app/Models/Stand/Stand.php
- app/Providers/AppServiceProvider.php
- lang/en/airlines/form.php
- lang/en/airlines/table.php
- lang/en/form.php
- lang/en/table.php
- tests/app/Filament/AirlineResourceTest.php
- Add a filament resource for airlines
- Add on creation option for copying stands from another airline
- Add a relation manager to allow terminals to be assigned to airlines from the page of a particular airline
- Add a relation manager to allow stands to be assigned to airlines from the page of a particular airline
> Airline admin

- app/Http/Livewire/RequestAStandForm.php
- tests/app/Http/Livewire/RequestAStandFormTest.php
Use a standard text input for request a stand, as the datepicker doesn't always play nicely.
> feat: easier to use date picker for request a stand

- app/Rules/Controller/ControllerPositionFrequency.php
- tests/app/Filament/ControllerPositionResourceTest.php
- tests/app/Rules/Controller/ControllerPositionFrequencyTest.php
Updates frequency validation to allow controller position frequencies with 8.33KHz spacing in preparation for the trial.
https://community.vatsim.uk/topic/38977-833khz-trial-uk-frequency-changes-phase-1/
> feat: 8.33KHz controller frequencies

- .github/workflows/test.yml
- .gitignore
- app/Rules/Controller/ControllerPositionFrequency.php
- tests/app/Filament/ControllerPositionResourceTest.php
- tests/app/Rules/Controller/ControllerPositionFrequencyTest.php
We regularly get transient issues where something goes wrong with codecov and therefore the build fails.
This change allows the build to pass.
> Codecov allow fail
